name: PR Validation
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
    - name: Checking the presence of the Traceability Marker in the PR title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        if echo "$PR_TITLE" | grep -iqP "^\[(New|BugFix|Infra|Breaking)\]"; then
          echo "PR title contains the traceability marker"
          exit 0
        else
          echo "Traceability marker missing"
          echo "Update your title with one of the following postfix"
          echo "(Infra,Bugfix,New,Breaking)"
          echo
          echo "e.g. $PR_TITLE (BugFix)"
          exit 1
        fi
