name: Pre Commit

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PreCommit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: |
        python -m pip install 'pre-commit<4.0.0'
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --verbose
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
